dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq --allow-unauthenticated
  - sudo apt-get install -qq bats
  - eval "$(GIMME_GO_VERSION=1.8.3 gimme)"

install: true

script:
  # Unit-test and build server
  - cd server/
  - ./gradlew build --info
  - cd ..

  # Unit-test and build integration server
  - cd github-integration/
  - ./gradlew build --info
  - cd ..

  # Launch local zally server
  - cd server/
  - ./gradlew bootRun > /dev/null &
  - echo $! > /tmp/zally_server.pid
  - cd ..

  # Wait until Spring Boot will start
  - while ! echo "GET / HTTP/1.0\n" | nc localhost 8080; do sleep 1; done

  # Test and build CLI
  - export ZALLY_GO_PATH="$GOPATH/src/github.com/zalando-incubator/zally"
  - mkdir -p $ZALLY_GO_PATH
  - cp -R . $ZALLY_GO_PATH
  - cd $ZALLY_GO_PATH/cli/zally
  - go get -v -t -tags=integration
  - ./test.sh integration
  - go build
  - cd $TRAVIS_BUILD_DIR

  # Kill Zally server instace
  - kill -9 `cat /tmp/zally_server.pid`

  # Unit-test web UI
  - cd web-ui
  - node --version
  - npm --version
  - npm install -q
  - npm test -- -i
  - npm run build
  - cd $TRAVIS_BUILD_DIR

after_success:
  # Upload test code coverage report for Zally server
  - bash <(curl -s https://codecov.io/bash) -f server/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally integration server
  - bash <(curl -s https://codecov.io/bash) -f github-integration/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally CLI
  - bash <(curl -s https://codecov.io/bash) -f $ZALLY_GO_PATH/cli/zally/coverage.txt -f $TRAVIS_BUILD_DIR/web-ui/target/coverage/lcov.info
