version: '2.1'
services:
  bark:
    build: ./github-integration
    depends_on:
    - postgres-bark
    links:
    - postgres-bark:postgres-bark.local
    - server:server.local
    ports:
    - "8081:8080"
    volumes:
    - "./github-integration/src/meta/credentials:/meta/credentials"
    environment:
    - MANAGEMENT_PORT=7979
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-bark.local:5432/bark
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - GITHUB_API_URL=https://api.github.com
    - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
    - GITHUB_SECRET=${GITHUB_SECRET}
    - ZALLY_URL=http://server.local:8000
    - CREDENTIALS_DIR=/meta/credentials
    - BARK_SERVER_URL=http://0.0.0.0:8081
  postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=zally
    ports:
    - "54321:5432"
  postgres-bark:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=bark
    ports:
    - "54322:5432"
