spring:
  profiles:
    active: production
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  oauth2:
    resource:
      tokenInfoUri: ${TOKEN_INFO_URI}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, metrics
  server:
    port: ${MANAGEMENT_PORT}

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

rules-config-path: "rules-config.conf"

zally:
  ignoreRules: S010, H001, S005
  cli:
    releasesPage: https://github.com/zalando/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0
---
spring.profiles: local
TOKEN_INFO_URI: https://auth.example.com/oauth2/tokeninfo
MANAGEMENT_PORT: 7979
