endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

server:
  port: 8000 # using the same port as the web-ui expects (see `docker-compose.yaml`)

management:
  server:
    port: 8000 # listening on the same port (`server` and `management.server`)

zally:
  cli:
    releasesPage: https://github.com/zalando/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0

TOKEN_INFO_URI: https://auth.example.com/oauth2/tokeninfo
