spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

security:
  basic:
    enabled: false

management.server.port: 0

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

zally:
  cli:
    releasesPage: https://github.com/zalando/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0