swagger: '2.0'

info:
 title: Zally Github Integration
 description: Zalando's Zally Linter Github Integration
 version: "1.1.0"
 contact:
   name: Team API Management
   email: team-api-management@zalando.de

host: "zally.overarching.zalan.do"

schemes:
  - https

basePath: /

securityDefinitions:
  oauth2:
    type: oauth2
    tokenUrl: https://somewhere.on.the.internet
    flow: password
    scopes:
      uid: submit API specification for validation

parameters:
  Authorization:
    name: Authorization
    in: header
    description: OAUTH2 (IAM)
    required: true
    type: string
    format: OAUTH2 (IAM)
  ValidationRequest:
    name: Request
    in: body
    description: Validation Request
    required: true
    schema:
      $ref: '#/definitions/ValidationRequest'

paths:
  '/api-validation':
    post:
      summary:
        API Validation
      description: |
        The API Validation bla bla bla
      parameters:
        - $ref: '#/parameters/Authorization'
        - $ref: '#/parameters/ValidationRequest'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: API swagger is OK
          schema:
            $ref: '#/definitions/LintingResponse'
        400:
          description: Input file not parsable
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
        default:
          description: An array of error objects
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
      security:
        - oauth2:
          - uid

definitions:
  ValidationRequest:
    type: object
    description: Request containing a validation request
    properties:
      api_definition:
        type: object
      api_definition_url:
        type: string
      ignoreRules:
        type: array
        items:
          type: string
