endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/barks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: de.zalando.zally.integration.config.JsonPostgresqlDialect

management.port: 0

tokens:
  accessTokenUri: https://auth.example.com/oauth2/access_token?realm=testing
  credentialsDirectory: src/test/resources/credentials
  token-configuration-list:
    - tokenId: zally
      scopes:
        - uid

zally:
  apiUrl: http://localhost:9099

github:
  apiUrl: http://localhost:8088
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890

bark:
  serverUrl: http://localhost:8080
