spring:
  profiles:
    active: production
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: de.zalando.zally.integration.config.JsonPostgresqlDialect
  oauth2:
    resource:
      tokenInfoUri: https://auth.example.com/oauth2/tokeninfo


management:
  endpoints:
    enabled: false
    health:
      enabled: true
    metrics:
      enabled: true
      sensitive: false
  server:
    port: 7979

tokens:
  accessTokenUri: https://auth.example.com/oauth2/access_token?realm=testing
  credentialsDirectory: /meta/credentials
  startAfterCreation: true
  token-configuration-list:
    - tokenId: zally
      scopes:
        - uid

zally:
  apiUrl: http://localhost:9099

github:
  apiUrl: http://localhost:8088
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890

bark:
  serverUrl: http://localhost:8080
