endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

security:
  basic:
    enabled: false

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

management.port: 8080
